#!/bin/sh
if (pidof dunst >/dev/null); then kill $(pidof dunst)
else ps axo rss,comm,pid | awk '{ proc_list[$2] += $1; } END \
{ for (proc in proc_list) { printf("%d\t%s\n", proc_list[proc],proc); }}' | sort -n | tail -n 20 | sort -rn | awk '{$1/=1024;printf "%.0fMB\t",$1}{print $2}' | xargs -0 notify-send -t 0
fi
exit 0
